### ISSUE TITLE
MIT or Apache License?

### ISSUE THREAD

**Issue by onkelbeh** [BaQs/pyAtome#1]
Hi,

on Pypi you have stated your software under 'Apache Software License' which could be:
 - Apache-1.0
 - Apache-1.1
 - Apache-2.0
 - Apache-2.0-with-LLVM-exceptions

here on github.com you state it's MIT, the link to the license text is broken. Please select a unique license on all platforms.

I'd like to make an ebuild for your integration in my [Gentoo Overlay for Home Assistant](https://github.com/onkelbeh/HomeAssistantRepository), so i'd need to know a proper license to publish.

PS: your requirements.txt is huge. Many of the listed libraries aren't used in the code anyway. And you should pin versions only when it's neccesary.

Thanks a lot.

 \B.

**Comment by BaQs** [comment]
Hello,

Honestly I don't know much about it. Do you have a proposal ? 
Don't hesitate to make a PR with the appropriate changes

And big up for your work on gentoo !

**Comment by onkelbeh** [comment]
Hi,
Thanks too, no, no lawyer in sight ;-)
at the bottom of my [README.md](https://github.com/onkelbeh/HomeAssistantRepository/blob/master/README.md) you'll find a license usage table from last years end, simply most of you guys use MIT. For my Gentoo overlay i use GPL-3.0 (like nearly all other Gentoo Repos do). Apache-2.0 is also very common.
Please let me know if you change it, so I can update this in my files, too.

**Comment by onkelbeh** [comment]
Ping :-)

**Comment by onkelbeh** [comment]
Ping again.

**Comment by BaQs** [comment]
Hello!
Sorry!!!! I've been so busy... I think ASL 2.0 will do.

**Comment by onkelbeh** [comment]
OK, you ASL 2.0?
Then the correct License String is "Apache-2.0".
I will update the Ebuilds, thanks.

**Comment by BaQs** [comment]
yep thx!
